IN-462: Send notification for runs that require manual intervention
eastgenomics/ansible-run-monitoring pull request #27
Opened 2024-02-19 17:25 UTC by JasonLing95

# Changes
- send notification for runs that have been on ida server for `ANSIBLE_WEEK` weeks long. 

Currently `ANSIBLE_WEEK` is set to 6 on ida server which is the line we define a run being old enough to be "deleted" if it fits all the other criteria (e.g. 002 project being created, uploaded on staging-52, jira ticket etc). This update will basically send a simple notification (like below) to Slack on run that have been dormant in ida server and fit none of the above criteria so that it doesn't fly under the radar.

<img width="1007" alt="Screenshot 2024-02-19 at 17 24 05" src="https://github.com/eastgenomics/ansible-run-monitoring/assets/60819172/efd1dbea-1ba8-44ef-9865-5776b2174dd1">

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/eastgenomics/ansible-run-monitoring/27)

2024-02-19 17:25 UTC, pep8speaks commented
Hello @JasonLing95! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`bin/util.py`](https://github.com/eastgenomics/ansible-run-monitoring/blob/a9d0677a631bdf6b328f8530c94b7df9b19f7e13/bin/util.py):

> [Line 177:80](https://github.com/eastgenomics/ansible-run-monitoring/blob/a9d0677a631bdf6b328f8530c94b7df9b19f7e13/bin/util.py#L177): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (91 > 79 characters)
> [Line 183:80](https://github.com/eastgenomics/ansible-run-monitoring/blob/a9d0677a631bdf6b328f8530c94b7df9b19f7e13/bin/util.py#L183): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (91 > 79 characters)
> [Line 184:80](https://github.com/eastgenomics/ansible-run-monitoring/blob/a9d0677a631bdf6b328f8530c94b7df9b19f7e13/bin/util.py#L184): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (151 > 79 characters)
> [Line 228:46](https://github.com/eastgenomics/ansible-run-monitoring/blob/a9d0677a631bdf6b328f8530c94b7df9b19f7e13/bin/util.py#L228): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'

* In the file [`main.py`](https://github.com/eastgenomics/ansible-run-monitoring/blob/a9d0677a631bdf6b328f8530c94b7df9b19f7e13/main.py):

> [Line 306:80](https://github.com/eastgenomics/ansible-run-monitoring/blob/a9d0677a631bdf6b328f8530c94b7df9b19f7e13/main.py#L306): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (84 > 79 characters)
> [Line 308:80](https://github.com/eastgenomics/ansible-run-monitoring/blob/a9d0677a631bdf6b328f8530c94b7df9b19f7e13/main.py#L308): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)
> [Line 455:80](https://github.com/eastgenomics/ansible-run-monitoring/blob/a9d0677a631bdf6b328f8530c94b7df9b19f7e13/main.py#L455): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (89 > 79 characters)

2024-02-20 16:56 UTC, jethror1 requested changes
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/ansible-run-monitoring/27)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @JasonLing95)

___
*[`main.py` line 458 at r1](https://reviewable.io/reviews/eastgenomics/ansible-run-monitoring/27#-Nr6RFtbAcD4jIHadO8b:-Nr6RFtbAcD4jIHadO8c:b-h4el3a) ([raw file](https://github.com/eastgenomics/ansible-run-monitoring/blob/a9d0677a631bdf6b328f8530c94b7df9b19f7e13/main.py#L458)):*
> ```Python
>             if check_age(created_date, today, ANSIBLE_WEEK):
>                 temp_manual_intervention.append(
>                     f"`{run_path}` :: {round(duration.days / 7, 2)} weeks"
> ```

would it be possible here to add its Jira status and a link to the ticket since I _think_ you have that info above? This would make it easier to review runs that are in the status "Data cannot be released", as these usually are fails that we can go manually delete



_Code quote:_
```Python
f"`{run_path}` :: {round(duration.days / 7, 2)} weeks"
```
___
*[`README.md` line 24 at r1](https://reviewable.io/reviews/eastgenomics/ansible-run-monitoring/27#-Nr6RfbNBeB1RrRSn_KN:-Nr6RfbNBeB1RrRSn_KO:b2nhh0h) ([raw file](https://github.com/eastgenomics/ansible-run-monitoring/blob/a9d0677a631bdf6b328f8530c94b7df9b19f7e13/README.md#L24)):*
> ```Markdown
> ## Script Workflow
> 
> - Script scheduled to run everyday by cron on ida server
> ```

Ida



_Code quote:_
```Markdown
ida
```


<!-- Sent from Reviewable.io -->

2024-02-22 09:42 UTC, JasonLing95 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/ansible-run-monitoring/27)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @jethror1)

___
*[`main.py` line 458 at r1](https://reviewable.io/reviews/eastgenomics/ansible-run-monitoring/27#-Nr6RFtbAcD4jIHadO8b:-NrFBWXj9LFBN1QS0XWs:b-ojhzfa) ([raw file](https://github.com/eastgenomics/ansible-run-monitoring/blob/a9d0677a631bdf6b328f8530c94b7df9b19f7e13/main.py#L458)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

would it be possible here to add its Jira status and a link to the ticket since I _think_ you have that info above? This would make it easier to review runs that are in the status "Data cannot be released", as these usually are fails that we can go manually delete
</blockquote></details>

added the Jira link + fail reason to the message
___
*[`README.md` line 24 at r1](https://reviewable.io/reviews/eastgenomics/ansible-run-monitoring/27#-Nr6RfbNBeB1RrRSn_KN:-NrFBVMD7ivEemMzYlz7:bb7f2mf) ([raw file](https://github.com/eastgenomics/ansible-run-monitoring/blob/a9d0677a631bdf6b328f8530c94b7df9b19f7e13/README.md#L24)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

Ida
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2024-02-22 10:31 UTC, jethror1 approved these changes
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/ansible-run-monitoring/27)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @JasonLing95)



<!-- Sent from Reviewable.io -->

2024-02-22 10:31 UTC, merged