v1.1.0 change deletion logic
eastgenomics/ansible-run-monitoring pull request #28
Opened 2024-03-06 10:10 UTC by jethror1

- started work on changing deletion logic to allow for weekly clearing of data
- intended behaviour is to run check on a Monday for runs to delete, then perform deletion on the Wednesday
- switch to also automatically delete runs which have a Jira ticket status in `DATA CANNOT BE RELEASED` and `DATA CANNOT BE PROCESSED` - fixes #18 
- refactored core logic into 2 functions:
  - `check_for_deletion()` - main logic for determining what meets criteria for deletion and storing in pickle file
  - `delete_runs()` - actually deletes the run data

2024-03-06 10:10 UTC, pep8speaks commented
Hello @jethror1! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`main.py`](https://github.com/eastgenomics/ansible-run-monitoring/blob/534456182b9b322272693a5daa26f311c385a9b3/main.py):

> [Line 93:5](https://github.com/eastgenomics/ansible-run-monitoring/blob/534456182b9b322272693a5daa26f311c385a9b3/main.py#L93): [E125](https://duckduckgo.com/?q=pep8%20E125) continuation line with same indent as next logical line
> [Line 138:80](https://github.com/eastgenomics/ansible-run-monitoring/blob/534456182b9b322272693a5daa26f311c385a9b3/main.py#L138): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)
> [Line 235:9](https://github.com/eastgenomics/ansible-run-monitoring/blob/534456182b9b322272693a5daa26f311c385a9b3/main.py#L235): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 297:5](https://github.com/eastgenomics/ansible-run-monitoring/blob/534456182b9b322272693a5daa26f311c385a9b3/main.py#L297): [E125](https://duckduckgo.com/?q=pep8%20E125) continuation line with same indent as next logical line
> [Line 439:80](https://github.com/eastgenomics/ansible-run-monitoring/blob/534456182b9b322272693a5daa26f311c385a9b3/main.py#L439): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (83 > 79 characters)
> [Line 458:80](https://github.com/eastgenomics/ansible-run-monitoring/blob/534456182b9b322272693a5daa26f311c385a9b3/main.py#L458): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (84 > 79 characters)

2024-03-15 15:30 UTC, JasonLing95 requested changes
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/ansible-run-monitoring/28)* status: all files reviewed, 6 unresolved discussions (waiting on @jethror1)

___
*[`monitor.py` line 82 at r2](https://reviewable.io/reviews/eastgenomics/ansible-run-monitoring/28#-Nt1bWTbBDpPit0BaoQo:-Nt1bWTbBDpPit0BaoQp:b-xrhmmk) ([raw file](https://github.com/eastgenomics/ansible-run-monitoring/blob/6f9c74b30072951413db43f7e7900a2a1a568d0e/monitor.py#L82)):*
> ```Python
> 
>     # fix required types
>     selected_env.seqs = selected_env.seqs.split(',')
> ```

could do strip() on each value in list
___
*[`monitor.py` line 83 at r2](https://reviewable.io/reviews/eastgenomics/ansible-run-monitoring/28#-Nt1dYB99vNiFTU8t7n1:-Nt1dYB99vNiFTU8t7n2:b-xrhmmk) ([raw file](https://github.com/eastgenomics/ansible-run-monitoring/blob/6f9c74b30072951413db43f7e7900a2a1a568d0e/monitor.py#L83)):*
> ```Python
>     # fix required types
>     selected_env.seqs = selected_env.seqs.split(',')
>     selected_env.jira_assay = selected_env.jira_assay.split(',')
> ```

could do strip() on each value in list
___
*[`monitor.py` line 187 at r2](https://reviewable.io/reviews/eastgenomics/ansible-run-monitoring/28#-Nt1eK0h1Ru9ViFO7vLK:-Nt1eK0h1Ru9ViFO7vLL:bmr49r0) ([raw file](https://github.com/eastgenomics/ansible-run-monitoring/blob/6f9c74b30072951413db43f7e7900a2a1a568d0e/monitor.py#L187)):*
> ```Python
>         if project_data:
>             # found 002 project => generate link
>             trimmed_id = project_data.get(
> ```

could check if `trimmed_id` is empty too, then url = "NA"
___
*[`monitor.py` line 409 at r2](https://reviewable.io/reviews/eastgenomics/ansible-run-monitoring/28#-Nt1go0lC2Ou3s1ieQ3T:-Nt1go0lC2Ou3s1ieQ3U:b-lyie15) ([raw file](https://github.com/eastgenomics/ansible-run-monitoring/blob/6f9c74b30072951413db43f7e7900a2a1a568d0e/monitor.py#L409)):*
> ```Python
>             continue
> 
>         deleted_runs.append(f"{genetics_dir}/{seq}/{run} {today}\n")
> ```

might want to move this into try clause as the delete my raise exception and not actually delete the run folder
___
*[`monitor.py` line 579 at r2](https://reviewable.io/reviews/eastgenomics/ansible-run-monitoring/28#-Nt1hK55Ci0IaPKE0eEH:-Nt1hK565MCKetKspG9i:be6m84h) ([raw file](https://github.com/eastgenomics/ansible-run-monitoring/blob/6f9c74b30072951413db43f7e7900a2a1a568d0e/monitor.py#L579)):*
> ```Python
>     )
> 
>     check_for_deletion(
> ```

could take env: SimpleNameSpace as an argument then that will cut down the amount of args in this function
___
*[`monitor.py` line 593 at r2](https://reviewable.io/reviews/eastgenomics/ansible-run-monitoring/28#-Nt1hYcVEN-8jEuxpcqx:-Nt1hYcVEN-8jEuxpcqy:be6m84h) ([raw file](https://github.com/eastgenomics/ansible-run-monitoring/blob/6f9c74b30072951413db43f7e7900a2a1a568d0e/monitor.py#L593)):*
> ```Python
>     )
> 
>     delete_runs(
> ```

could take env: SimpleNameSpace as an argument then that will cut down the amount of args in this function


<!-- Sent from Reviewable.io -->

2024-03-18 10:04 UTC, jethror1 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/ansible-run-monitoring/28)* status: all files reviewed, 6 unresolved discussions (waiting on @JasonLing95)

___
*[`monitor.py` line 82 at r2](https://reviewable.io/reviews/eastgenomics/ansible-run-monitoring/28#-Nt1bWTbBDpPit0BaoQo:-NtFzIMO9g-32GBnyb0M:b-896fix) ([raw file](https://github.com/eastgenomics/ansible-run-monitoring/blob/6f9c74b30072951413db43f7e7900a2a1a568d0e/monitor.py#L82)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

could do strip() on each value in list
</blockquote></details>

Done.
___
*[`monitor.py` line 83 at r2](https://reviewable.io/reviews/eastgenomics/ansible-run-monitoring/28#-Nt1dYB99vNiFTU8t7n1:-NtFzIkrD2-CJufynjbY:b-896fix) ([raw file](https://github.com/eastgenomics/ansible-run-monitoring/blob/6f9c74b30072951413db43f7e7900a2a1a568d0e/monitor.py#L83)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

could do strip() on each value in list
</blockquote></details>

Done.
___
*[`monitor.py` line 187 at r2](https://reviewable.io/reviews/eastgenomics/ansible-run-monitoring/28#-Nt1eK0h1Ru9ViFO7vLK:-NtG-Npo2TzCBiQqR5Wf:bi86gn1) ([raw file](https://github.com/eastgenomics/ansible-run-monitoring/blob/6f9c74b30072951413db43f7e7900a2a1a568d0e/monitor.py#L187)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

could check if `trimmed_id` is empty too, then url = "NA"
</blockquote></details>

if there is a return from finding projects, then there always will be described data to get a project ID from won't there? If no projects are found then `utils.get_describe_data()` just returns an empty dict
___
*[`monitor.py` line 409 at r2](https://reviewable.io/reviews/eastgenomics/ansible-run-monitoring/28#-Nt1go0lC2Ou3s1ieQ3T:-NtG00oU09cSvXPOAVJA:b59m4dk) ([raw file](https://github.com/eastgenomics/ansible-run-monitoring/blob/6f9c74b30072951413db43f7e7900a2a1a568d0e/monitor.py#L409)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

might want to move this into try clause as the delete my raise exception and not actually delete the run folder
</blockquote></details>

good point, done
___
*[`monitor.py` line 579 at r2](https://reviewable.io/reviews/eastgenomics/ansible-run-monitoring/28#-Nt1hK55Ci0IaPKE0eEH:-NtG05lZ7bXDajj6esQM:bk77e8k) ([raw file](https://github.com/eastgenomics/ansible-run-monitoring/blob/6f9c74b30072951413db43f7e7900a2a1a568d0e/monitor.py#L579)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

could take env: SimpleNameSpace as an argument then that will cut down the amount of args in this function
</blockquote></details>

I could but I also don't want to change it everywhere now
___
*[`monitor.py` line 593 at r2](https://reviewable.io/reviews/eastgenomics/ansible-run-monitoring/28#-Nt1hYcVEN-8jEuxpcqx:-NtG09etAAiLoiSMFwas:bnj7hl0) ([raw file](https://github.com/eastgenomics/ansible-run-monitoring/blob/6f9c74b30072951413db43f7e7900a2a1a568d0e/monitor.py#L593)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

could take env: SimpleNameSpace as an argument then that will cut down the amount of args in this function
</blockquote></details>

same as above


<!-- Sent from Reviewable.io -->

2024-03-18 10:28 UTC, JasonLing95 reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/ansible-run-monitoring/28)* status: 5 of 6 files reviewed, all discussions resolved (waiting on @jethror1)



<!-- Sent from Reviewable.io -->

2024-03-18 10:28 UTC, JasonLing95 approved these changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/ansible-run-monitoring/28)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jethror1)



<!-- Sent from Reviewable.io -->

2024-03-18 10:28 UTC, merged